apiVersion: nodes.pokt.network/v1alpha1
kind: PocketValidator
metadata:
  name: v1-validator4
spec:
  collection:
    name: "primary"
  pocketImage: "ghcr.io/pokt-network/pocket-v1:sha-f0400e8-dev"
  privateKey:
    secretKeyRef:
      name: v1-validator4
      key: private_key
  postgres:
    user:
      secretKeyRef:
        name: pocket-postgres-postgresql
        key: username
    password:
      secretKeyRef:
        name: pocket-postgres-postgresql
        key: password
    host: pocket-postgres-postgresql
    port: "5432"
    database: postgres
    schema: validator4
---
apiVersion: v1
kind: Secret
metadata:
  name: v1-validator4
type: Opaque
stringData:
  private_key: "c6c136d010d07d7f5e9944aa3594a10f9210dd3e26ebc1bc1516a6d957fd0df353ee26c82826694ffe1773d7b60d5f20dd9e91bdf8745544711bec5ff9c6fb4a"
