apiVersion: nodes.pokt.network/v1alpha1
kind: PocketValidator
metadata:
  name: v1-validator2
spec:
  collection:
    name: "primary"
  pocketImage: "ghcr.io/pokt-network/pocket-v1:sha-f0400e8-dev"
  privateKey:
    secretKeyRef:
      name: v1-validator2
      key: private_key
  postgres:
    user:
      secretKeyRef:
        name: pocket-postgres-postgresql
        key: username
    password:
      secretKeyRef:
        name: pocket-postgres-postgresql
        key: password
    host: pocket-postgres-postgresql
    port: "5432"
    database: postgres
    schema: validator2
---
apiVersion: v1
kind: Secret
metadata:
  name: v1-validator2
type: Opaque
stringData:
  private_key: "b37d3ba2f232060c41ba1177fea6008d885fcccad6826d64ee7d49f94d1dbc49a8b6be75d7551da093f788f7286c3a9cb885cfc8e52710eac5f1d5e5b4bf19b2"
